export const message = {
  RegisterUserSuccess: `User Registered Successfully`,
  alreadyUseEmail: `Email Already Taken Please choose another One.`,
  loginSuccess: `Login successfully.`,
  emailSame: `Alternate email should not be same with email address.`,
  notFound: `User Not Found`,
  notMatchPassword: `Password not match`,
  noUser: `No user from google`,
  successSent: `Please check your email address for instructions to reset your password.`,
  successReset: `Password has been successfully reset for `,
  notMatchOTP: `Wrong verification code, please try again`,
  otpExpire: `The confirmation code has expired. Please request a new code.`,
  tryDiffPass: `Password already in use, Please try different Password`,
  successFetched: `Fetched Successfully`,
  successChangedPass: `Password has been successfully updated.`,
  passWrong: `Password is wrong.`,
  alreadyInUse: `Email Already Taken Please choose another One.`,
  successUpdate: `Record has been updated Successfully`,
};
